name: Deploy Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Create swagger
        run: npm run swagger
      - name: Build
        run: npm run build
      - name: Create certificate creation command
        env: 
          EMAIL: ${{ secrets.EMAIL }}
          DOMAIN: ${{ secrets.DOMAIN }}
        run: |
          cd .platform/hooks/postdeploy
          rm 00_get_certificate.sh
          touch 00_get_certificate.sh
          echo "#!/usr/bin/env bash" >> 00_get_certificate.sh
          echo "sudo certbot -n -d $DOMAIN --nginx --agree-tos --email $EMAIL" >> 00_get_certificate.sh
          cd ..    
      - name: Generate deployment zip
        run: zip -r deploy.zip * .[^.]* -x "**node_modules**" -x "**src**"
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time    
      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'    
      - name: Deploy to EBS
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "littlePaw"
          environment_name: "LittlePaw-env"
          version_label: "version-label-${{ steps.format-time.outputs.replaced }}"
          region: "us-east-1"
          deployment_package: deploy.zip
      - name: Deployed!
        run: echo App deployed to ELB
