name: Scan Vulnerabilities and Send Report to Discord

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  scan_and_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nikto
        run: |
          sudo apt-get update
          sudo apt-get install -y nikto

      - name: Nikto Scan with Custom Options
        run: |
          echo "Scanning with custom options"
          nikto -Display 1234EP -o nikto-report.html -Format htm -Tuning 123bde -host https://main.d3jn59dldttup9.amplifyapp.com/welcome
          cat nikto-report.html

      - name: Modify HTML Report Title
        run: |
          sed -i 's|<table class="headerTable" width="300"><tr><td>.*</td></tr></table>|<table class="headerTable" width="300"><tr><td>Vulnerabilidades de la página main.d3jn59dldttup9.amplifyapp.com / IP: 18.165.98.62, Puerto: 443</td></tr></table>|' nikto-report.html
          echo "HTML title updated."

      - name: Install Nmap and XSLTProc
        run: |
          sudo apt-get install -y nmap xsltproc

      - name: Nmap Scan and Export to XML
        run: |
          echo "Scanning with Nmap using default vuln script"
          nmap -sV --script vuln -oX nmap-report1.xml main.d3jn59dldttup9.amplifyapp.com
          echo "Nmap vuln scan report generated."
          echo "Scanning with Nmap using vulners script"
          nmap -sV --script vulners -oX nmap-report2.xml main.d3jn59dldttup9.amplifyapp.com
          echo "Nmap vulners scan report generated."

      - name: Convert XML Reports to HTML
        run: |
          xsltproc -o nmap-report1.html nmap-report1.xml
          xsltproc -o nmap-report2.html nmap-report2.xml
          echo "Nmap reports converted to HTML."

      # - name: Convert JSON to CSV using SploitScan
      #   run: |
      #     git clone https://github.com/xaitax/SploitScan.git
      #     cd SploitScan
      #     pip3 install -r requirements.txt
      #     python3 sploitscan.py -e csv -i ../nmap-report.json nmap-report.csv
      #     cd ..

      - name: Send Nikto HTML Report to Discord
        run: |
          curl -H "Content-Type: multipart/form-data" \
               -F "payload_json={\"content\": \"Nikto Scan Report with Specific Tuning Options Attached.\"}" \
               -F "file=@nikto-report.html" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Nmap Reports to Discord
        run: |
          echo "Sending Nmap vuln scan report to Discord."
          curl -H "Content-Type: multipart/form-data" \
               -F "payload_json={\"content\": \"Nmap Vuln Scan Report.\"}" \
               -F "file=@nmap-report1.html" \
               ${{ secrets.DISCORD_WEBHOOK }}
          echo "Sending Nmap vulners scan report to Discord."
          curl -H "Content-Type: multipart/form-data" \
               -F "payload_json={\"content\": \"Nmap Vulners Scan Report.\"}" \
               -F "file=@nmap-report2.html" \
               ${{ secrets.DISCORD_WEBHOOK }}