name: Scan Vulnerabilities and Send Report to Discord

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  scan_and_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nikto
        run: |
          sudo apt-get update
          sudo apt-get install -y nikto

      - name: Nikto Scan with Specific Tuning Options
        run: |
          echo "Scanning main domain with specific tuning options"
          nikto -h https://main.d3jn59dldttup9.amplifyapp.com/welcome -output nikto-report.html -Format htm -Tuning 24789d
          cat nikto-report.html

      - name: Send HTML Report to Discord
        run: |
          curl -H "Content-Type: multipart/form-data" \
               -F "payload_json={\"content\": \"Nikto Scan Report with Specific Tuning Options Attached.\"}" \
               -F "file=@nikto-report.html" \
               ${{ secrets.DISCORD_WEBHOOK }}
