name: Scan Vulnerabilities and Send Report to Discord

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  scan_and_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nikto
        run: |
          sudo apt-get update
          sudo apt-get install -y nikto

      - name: Nikto Scan with Custom Options
        run: |
          echo "Scanning with custom options"
          nikto -Display 1234EP -o nikto-report.html -Format htm -Tuning 123bde -host https://main.d3jn59dldttup9.amplifyapp.com/welcome
          cat nikto-report.html

      - name: Modify HTML Report Title
        run: |
          sed -i 's|<table class="headerTable" width="300"><tr><td>.*</td></tr></table>|<table class="headerTable" width="300"><tr><td>Vulnerabilidades de la página main.d3jn59dldttup9.amplifyapp.com / IP: 18.165.98.62, Puerto: 443</td></tr></table>|' nikto-report.html
          echo "HTML title updated."

      - name: Install Nmap
        run: |
          sudo apt-get install -y nmap

      - name: Nmap Scan and Export to JSON
        run: |
          echo "Scanning with Nmap"
          nmap -sV --script vulners -oX nmap-report.xml https://main.d3jn59dldttup9.amplifyapp.com/welcome
          python3 -c "import xml.etree.ElementTree as ET; import json; print(json.dumps(ET.tostring(ET.parse('nmap-report.xml').getroot()).decode(), indent=4))" > nmap-report.json

      - name: Install tabulate module
        run: |
          pip install tabulate

      - name: Convert JSON to HTML using SploitScan
        run: |
          git clone https://github.com/xaitax/SploitScan.git
          cd SploitScan
          python3 sploitscan.py -i ../nmap-report.json -o nmap-report.html
          cd ..

      - name: Send Nikto HTML Report to Discord
        run: |
          curl -H "Content-Type: multipart/form-data" \
               -F "payload_json={\"content\": \"Nikto Scan Report with Specific Tuning Options Attached.\"}" \
               -F "file=@nikto-report.html" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Nmap HTML Report to Discord
        run: |
          curl -H "Content-Type: multipart/form-data" \
               -F "payload_json={\"content\": \"Nmap Scan Report Exported to HTML.\"}" \
               -F "file=@nmap-report.html" \
               ${{ secrets.DISCORD_WEBHOOK }}
